name: SwapHotBar
version: ${project.version}
main: cn.kevyn.swaphotbar.SwapHotBar
api-version: 1.18
author: kevyn
description: allow players to swap hotbar by pressing shift + mouse wheel.
website: kevyn.cn
permissions:
  shb.switch:
    default: true
  shb.reload:
    default: op
commands:
  shb-reload:
    description: you can use this command to reload the config file
    permission: shb.reload
  shb-on:
    description: you can use this command to switch on the swap function on you.
    permission: shb.switch
  shb-off:
    description: you can use this command to switch off the swap function on you.
    permission: shb.switch