name: SwapHotBar
version: ${project.version}
main: cn.kevyn.swaphotbar.SwapHotBar
api-version: 1.13
author: kevyn
description: allow players to swap hotbar by pressing shift + mouse wheel.
website: kevyn.cn
commands:
  shb:
    description: SwapHotBar's commands
    usage: /shb reload | ...
